#!/usr/bin/env bash
# From: https://github.com/ulissesalmeida/dotfiles/blob/master/script/osx_customization

# Load utils
source ${DOTFILES}/scripts/utils

print_question 'Starting OS X Customizations...\n'

# Save screenshots in ~/Pictures/Screenshots folder
mkdir $HOME/Pictures/Screenshots
defaults write com.apple.screencapture location -string "$HOME/Pictures/Screenshots"

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# Turn off keyboard illumination when computer is not used for 30 seconds"
defaults write com.apple.BezelServices kDimTime -int 30

# Make keyboard cursor faster
defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 2

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0


###############################################################################
# Finder
###############################################################################

# Show Path bar in Finder
defaults write com.apple.finder ShowPathbar -bool true

# Show sidebar on Finder
defaults write com.apple.finder ShowSidebar -bool true

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

# Avoid creation of .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Set default Finder path.
# For desktop, use `PfDe`.
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfHm"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

# Show the ~/Library folder
chflags nohidden ~/Library

# Show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Empty Trash securely by default
defaults write com.apple.finder EmptyTrashSecurely -bool true

# Enables the macOS screensaver password immediately (for better security)
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0


###############################################################################
# Dock
###############################################################################
# Set Dock zoom size
defaults write com.apple.dock magnification -int 0

# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true


### Security configurations

# Adds a Found this computer? message to the login screen (for machine recovery)
sudo defaults write /Library/Preferences/com.apple.loginwindow \
   LoginwindowText \
   "Found this computer? Please contact Elaine Naomi Watanabe at elaine.watanabe@plataformatec.com"


# Enable Firewall
sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1
sudo launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist 2>/dev/null

# Set language, timezone and text formats
defaults write NSGlobalDomain AppleLanguages -array "en-BR"
defaults write NSGlobalDomain AppleLocale -string "en_BR"
sudo systemsetup -settimezone "America/Sao_Paulo" > /dev/null

# Disable the “Are you sure you want to open this application?” dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Disable the over-the-top focus ring animation
defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

# Trackpad: enable tap to click for this user and for the login screen
# defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
# defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
# defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1


###############################################################################
# Kill affected applications
###############################################################################
for app in Finder Dock SystemUIServer
do
  killall "$app" >/dev/null 2>&1
done

